accounts/urls.py
"""Defines URL patterns for accounts"""

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
    # Account Settings
    path('settings/', views.settings, name='settings'),
    # View friends list
    path('<str:username>/friends/', views.friends_list, name='friends_list'),
    # View pending friend requests
    path('friend_requests/', views.view_friend_requests, name='view_friend_requests'),
    # Send friend request
    path('send_friend_request/<str:sender_username>/<str:receiver_username>/', views.send_friend_request, name='send_friend_request'),
    # Process friend request
    path('friend_requests/<int:request_id>/<str:action>/', views.process_friend_request, name='process_friend_request'),
]

sm_project/urls.py
from django.contrib import admin
from django.urls import path, include
from social_media import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('social_media.urls')),
] 

social_media/urls.py
"""Defines URL patterns for social_media"""

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'social_media'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # User page
    path('profile/<str:username>/', views.profile, name='profile'),
    # Create new post
    path('new_post/', views.new_post, name='new_post'),
    # View post
    path('posts/<int:post_id>/', views.post, name="post"),
    # Delete post
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    # Search
    path('search/', views.search, name='search'),
    # Create new comment
    path('posts/<int:post_id>/new_comment/', views.new_comment, name='new_comment'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_media/models.py
from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User

class Post(models.Model):
    """A post the user makes to the app."""
    caption = models.CharField(max_length=50)
    image = ResizedImageField(size=[250,250], upload_to='social_media/images/')
    created_on = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.url
    
class Comment(models.Model):
    """A comment a user leaves on a post."""
    comment = models.CharField(max_length=50)
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

social_media/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    """Create new post"""
    class Meta:
        model = Post
        fields = ['caption', 'image']
        labels = {'caption': 'Post Caption', 'image': 'Post Image'}

class CommentForm(forms.ModelForm):
    """Create new comment"""
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment': 'New Comment'}

social_media/views.py
from django.shortcuts import render, redirect, get_object_or_404
from social_media.models import Post, Comment
from django.http import Http404
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
from django.contrib.auth.models import User

def index(request):
    """Home page of site"""
    if request.user.is_authenticated:
        username = request.user.username
        feed = Post.objects.exclude(owner=request.user).order_by('created_on').reverse()
    else:
        username = None
        feed = None
    context = {
        'username': username,
        'feed': feed,
    }
    return render(request, 'social_media/index.html', context)

@login_required
def profile(request, username):
    """Show user profile"""
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, owner=user)
    posts = Post.objects.filter(owner=user).order_by('created_on')
    friends = profile.friends.all()
    context = {
        'user': user,
        'posts': posts,
        'profile': profile,
        'friends': friends,
    }
    return render(request, 'social_media/profile.html', context)
    
@login_required
def new_post(request):
    """Create a new post"""
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('social_media:profile', username=request.user.username)
    return render(request, 'social_media/new_post.html', {'form': form})

@login_required
def delete_post(request, post_id):
    """Delete a post"""
    post = Post.objects.get(pk=post_id)
    if request.method != 'POST':
        post.delete()
    return redirect('social_media:profile', username=request.user.username)
    
@login_required    
def post(request, post_id):
    """Show a post from user"""
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post)
    if not comments.exists():
        comments = None

    owner_username = post.owner.username
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None
    context = {
        'post': post,
        'username': username,
        'owner_username': owner_username,
        'comments': comments
    }
    return render(request, 'social_media/post.html', context)

def search(request):
    """Search for other profiles"""
    query = request.GET.get('search', '')
    if query:
        results = Profile.objects.filter(owner__username__icontains=query)
    else:
        results = Profile.objects.none()
    context = {
        'query': query,
        'results': results, 
    }
    return render(request, 'social_media/search.html', context)

@login_required  
def new_comment(request, post_id):
    """Create a new comment on post"""
    post = get_object_or_404(Post, pk=post_id)
    owner = request.user

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.owner = owner
            new_comment.save()
            return redirect('social_media:post', post_id=post.pk)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'social_media/new_comment.html', context)

social_media/templates/social_media/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SM</title>
  <link rel="stylesheet" href="{% static 'social_media/styles.css' %}">

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
    <div class="container-fluid">
      <div class="d-flex align-items-left">
        <a class="navbar-brand" href="{% url 'social_media:index' %}">Home</a>
        {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'social_media:profile' user.username %}">Profile</a>
        {% endif %}    
      </div>
      {% if user.is_authenticated %}
        <div>
          <form action="{% url 'social_media:search' %}" method="get">
            <input name="search" type="text" placeholder="Search Profile...">
            <button name="submit">Search</button>
          </form>
        </div>
      {% else %}
        <div class="ml-auto">
          <a class="navbar-brand" href="{% url 'accounts:login' %}">Log In</a>
          <a class="navbar-brand" href="{% url 'accounts:register' %}">Register</a>
        </div>  
      {% endif %}
    </div>
  </nav>

  <main class="container">
    <!-- <div class="pb-2 mb-2 border-bottom text-center">
      {% block page_header %}{% endblock page_header %}
    </div> -->
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

social_media/templates/social_media/index.html
{% extends 'social_media/base.html' %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="container mt-4">
      {% for post in feed %}
        <div class="row justify-content-center mb-4">
          <div class="col-md-7">
            <div class="card text-center">
              <div class="card-body">
                <a href="{% url 'social_media:post' post.pk %}">
                  <img src="{{ post.image.url }}" class="img-fluid card-img-top" alt="Post Image"/>
                </a>
                <p class="mt-2">{{ post.caption }}</p>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <p>No posts in feed.</p>
      {% endfor %}
    </div>
  {% else %}
    <div class="p-3 mb-4 bg-light border rounded-3">
      <div class="container-fluid py-4">
        <h1 class="display-3">"site name here - tbd"</h1>
        <p class="lead">
          Create your own account to connect with friends, share and view pictures, and comment on posts!
        </p>
        <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
      </div>
    </div>
  {% endif %}
{% endblock content %}

social_media/templates/social_media/new_comment.html
{% extends 'social_media/base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2 class="text-center mb-4">New Comment</h2>
    <form action="{% url 'social_media:new_comment' post.pk %}" method="post" class="w-50 mx-auto">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary w-100">Submit Comment</button>
    </form>
  </div>
{% endblock content %}

social_media/templates/social_media/new_post.html
{% extends 'social_media/base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2 class="text-center mb-4">Create a New Post</h2>
    <form action="{% url 'social_media:new_post' %}" method="post" enctype="multipart/form-data" class="w-50 mx-auto">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary w-100">Create Post</button>
    </form>
  </div>
{% endblock content %}

social_media/templates/social_media/post.html
{% extends 'social_media/base.html' %}

{% block content %}
  <div class="container">
    <div class="d-flex flex-column align-items-center mb-4">
      <img src="{{ post.image.url }}" class="img-fluid border rounded shadow mb-3" style="width: 500px; height: auto;" />
      <h1 class="text-center">{{ post.caption }}</h1>
      <p class="text-muted">{{ post.created_on|date:"F d, Y" }} - {{ post.created_on|time:"H:i" }}</p>
    </div>

    <div class="card w-75 mx-auto mb-4">
      <div class="card-header">
        <h5 class="card-title mb-0">Comments</h5>
      </div>
      <ul class="list-group list-group-flush">
        {% for c in comments %}
          <li class="list-group-item">
            <strong>{{ c.owner.username }}:</strong> {{ c.comment }}
          </li>
        {% empty %}
          <li class="list-group-item text-center">No comments yet</li>
        {% endfor %}
      </ul>
    </div>

    <div class="text-center">
      <a href="{% url 'social_media:new_comment' post.pk %}" class="btn btn-primary mb-3">Add a Comment</a>
    </div>

    {% if username == owner_username %}
      <div class="text-center">
        <a href="{% url 'social_media:delete_post' post.pk %}" class="btn btn-danger">Delete Post</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}

social_media/templates/social_media/profile.html
{% extends 'social_media/base.html' %}

{% block content %}
  <div class="text-center mb-4">
    <img src="{{ profile.profile_pic.url }}" class="rounded-circle" style="width: 50px; height: 50px;"/>
    <h2 class="mt-3">About Me:</h2>
    <div class="bio-box bg-info text-dark p-3 rounded shadow">
        <p>{{ profile.bio }}</p>
    </div>
  </div>

  <div class="d-flex">
    {% if request.user == user %}
      <a class="btn btn-info me-2" href="{% url 'social_media:new_post' %}">New Post</a>
      <a class="btn btn-info me-2" href="{% url 'accounts:settings' %}">Account Settings</a>
      <a class="btn btn-info me-2" href="{% url 'accounts:friends_list' user.username %}">Friends</a>
      <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-info me-2" name="submit">Log out</button>
      </form>
    {% else %}
      <a href="{% url 'accounts:send_friend_request' request.user.username user.username %}" class="btn btn-info me-2">Send Friend Request</a>
    {% endif %}
  </div>
  
  <div class="d-flex flex-wrap justify-content-left mb-4 mt-4">
    {% for post in posts %}
      <a href="{% url 'social_media:post' post.pk %}" class="m-2">
        <img src="{{ post.image.url }}" class="img-fluid border rounded shadow" style="width: 200px; height: auto;"/>
      </a>
    {% empty %}
      <p>Empty Profile</p>
    {% endfor %}
  </div>
{% endblock content %} 

social_media/templates/social_media/search.html
{% extends 'social_media/base.html' %}


{% block content %}
  <div class="container mt-4">
    <h2 class="text-center">Search Results for "{{ query }}"</h2>

    {% if results %}
      <ul class="list-group list-group-flush w-50 mx-auto mt-3">
        {% for user in results %}
          <li class="list-group-item text-center">
            <a href="{% url 'social_media:profile' user.owner.username %}" class="text-decoration-none text-muted">
              {{ user.owner.username }}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-center text-muted mt-3">No profiles found matching "{{ query }}"</p>
    {% endif %}
  </div>
{% endblock content %}